name: CI build

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: guitarpractice
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install poetry==1.1.2
          poetry export --dev -f requirements.txt > requirements.txt
          pip install -r requirements.txt
      - name: Security linting
        uses: jpetrucciani/bandit-check@1.6.2
      - name: Linting with flake8 and mypy
        uses: ricardochaves/python-lint@v1.1.0
        with:
          python-root-list: "."
          use-mypy: true
          use-flake8: true
          use-pylint: false
          use-pycodestyle: false
          use-black: false
          use-isort: false
          extra-mypy-options: "--ignore-missing-imports"
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - name: Test with pytest
        run: |
          pytest --cov=. --cov-report xml
      - name: Coverage analysis
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./coverage.xml
